# Generated by Django 5.0.6 on 2024-07-08 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='financialinstrument',
            table='bias_app_FinancialInstrument',
        ),
    ]
